FROM alpine:3.23
RUN addgroup -g 1000 -S mcp && adduser -u 1000 -S mcp -G mcp
ARG TARGETPLATFORM
COPY --chown=mcp:mcp $TARGETPLATFORM/mcp-victoriatraces /usr/local/bin/mcp-victoriatraces
RUN chmod +x /usr/local/bin/mcp-victoriatraces
USER mcp
WORKDIR /home/mcp
ENTRYPOINT [ "/usr/local/bin/mcp-victoriatraces" ]
