name: build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1

      - name: Check licenses and vulnerabilities
        run: make check

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

      - name: Tests
        run: make test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and release
        uses: goreleaser/goreleaser-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          args: release --clean --verbose --timeout 60m -f .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: |
          if [[ "${{ github.ref_type }}" != "tag" ]]; then
            git fetch --tags
          else
            echo "Skipping tag fetch - already on tag ${{ github.ref_name }}"
          fi

      - name: Update server.json version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          else
            LATEST_TAG=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$' | head -n 1)
            [ -z "$LATEST_TAG" ] && { echo "No release tag found"; exit 1; }
            TAG_VERSION=$(echo "$LATEST_TAG" | sed 's/^v//')
            echo "Using latest tag: $LATEST_TAG"
          fi
          sed -i "s/\${VERSION}/$TAG_VERSION/g" server.json
          echo "Version: $TAG_VERSION"

      - name: Validate configuration
        run: |
          python3 -m json.tool server.json > /dev/null && echo "Configuration valid" || exit 1

      - name: Display final server.json
        run: |
          echo "Final server.json contents:"
          cat server.json

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.2.3/mcp-publisher_1.2.3_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish
